### ISSUE TITLE
Feature request: filtering out abstract classes

### ISSUE THREAD

**Issue by robinklaassen** [ramonhagenaars/barentsz#2]
While developing a certain machine learning game, I "discovered" ;) that it would be very useful to have the option to automatically filter out abstract classes when using `discover_classes`. I would imagine a parameter `exclude_abstract` with default value `False`.

I might just write a PR for this myself :)

**Comment by ramonhagenaars** [comment]
Hi @robinklaassen,

A machine learning game, that sounds interesting.

> I "discovered"

I see what you did there. 😉 

Your request seems valid, though I would rather see a more generic solution than adding an extra exclude parameter. The already existing `exclude` parameter could be extended such that it accepts one or more predicates that determine exclusion given a value (`type`).

The type of the updated `exclude` parameter would thus become:
```python
Union[Iterable[Union[type, Callable[[type], bool]]], type, Callable[[type], bool]]
```

The above type notation seems a bit daunting I confess. Introducing an alias for that predicate may help making it more readible:
```python
exclude_pred = Callable[[type], bool]
Union[type, exclude_pred, Iterable[Union[type, exclude_pred]]]
```

With this, one could exclude anything by providing corresponding predicates, like so:
```python
discover_classes('.', exclude=is_abstract)
discover_classes('.', exclude=[has_name_that_starts_with_g])
discover_classes('.', exclude=[MyExcludedBaseClass, lambda _: random.choice([True, False])])
...
```

**Comment by robinklaassen** [comment]
Hey @ramonhagenaars,

Thanks for the clear reply. I agree with keeping the library more generic, it's easy enough to implement any necessary predicates outside of `barentsz`, and your proposed solution adds support for a ton of customized solutions. I'll try and rewrite the PR according to your suggestion, somewhere this week.

**Comment by ramonhagenaars** [comment]
Thank you @robinklaassen. This feature (your pull request) has been merged and [released](https://pypi.org/project/barentsz/).

I will now close this issue.
